### PR TITLE
Obervability: Wait for OpenTelemetry operator pod to be ready

### LINKED ISSUE #548: Observability: `up spaces init` fails to apply the telemetry collector
### What happened?
`up space init` with observability enabled checks if the telemetry operator is installed as a prerequisite, and if not, it installs it before applying the spaces helm chart. To check if the telemetry-operator is installed, it checks for the CRD of OpentelemetryCollector. 

The spaces chart contains the Space level OpenTelmetryCollector resource. 

In the time when the CRD is ready, and when the Spaces chart is applied, the OpenTelmetry operator is not actually Running yet, and its mutating webhook for OpenTelemetryCollector fails, resulting in the OpenTelemetryCollector not being applied, and the `up space init` erroring out.

```bash
 INFO  Setting defaults for vanilla Kubernetes (type kind)
 WARNING  One or more required prerequisites are not installed:

❌ cert-manager
❌ universal-crossplane
❌ ingress-nginx
❌ provider-kubernetes
❌ provider-helm
❌ opentelemetry-operator

Would you like to install them now? [y/N]: Yes

  ✓   [1/6]: Installing cert-manager
  ✓   [2/6]: Installing universal-crossplane
  ✓   [3/6]: Installing ingress-nginx
  ✓   [4/6]: Installing provider-kubernetes
  ✓   [5/6]: Installing provider-helm
  ✓   [6/6]: Installing opentelemetry-operator
 INFO  Required prerequisites met!
 INFO  Proceeding with Upbound Spaces installation...
  ✓   [1/3]: Creating pull secret upbound-pull-secret
 ▄ [2/3]: Initializing Space components (6s)

up: error: space.initCmd.Run(): 1 error occurred:
           	* Internal error occurred: failed calling webhook "mopentelemetrycollector.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook.opentelemetry-operator.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s": dial tcp 10.96.142.160:443: connect: connection refused
```

Epic #https://github.com/upbound/spaces/issues/934

### How can we reproduce it?

Local env, create kind cluster and run:
```bash
 up space init --token-file="../key.json" "v1.4.0-rc.0.331.g417a41db" \
  --set "account=bob" \
  --set "features.alpha.observability.enabled=true"
```

### What environment did it happen in?

running locally, but I think it will happen to all fresh Spaces installations, or the ones just enabling Observability

### PR DESCRIPTION
**Pull request by lsviben**
### Description of your changes

Adds a wait on the installation step of the OpenTelmetry Operator for the operator pod to be ready.

This fixes the issue in #548 which was failing the Spaces installation as the webhook was not ready to review the Space level OpenTelemetryCollector resource.

Fixes #548 

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

locally built binary with `make` and then ran `up space init`
```bash
_output/bin/darwin_arm64/up space init --token-file="../key.json" "v1.4.0-rc.0.331.g417a41db" \
  --set "account=bob" \
  --set "features.alpha.observability.enabled=true"
 INFO  Setting defaults for vanilla Kubernetes (type kind)
 WARNING  One or more required prerequisites are not installed:

❌ cert-manager
❌ universal-crossplane
❌ ingress-nginx
❌ provider-kubernetes
❌ provider-helm
❌ opentelemetry-operator

Would you like to install them now? [y/N]: Yes

  ✓   [1/6]: Installing cert-manager
  ✓   [2/6]: Installing universal-crossplane
  ✓   [3/6]: Installing ingress-nginx
  ✓   [4/6]: Installing provider-kubernetes
  ✓   [5/6]: Installing provider-helm
  ✓   [6/6]: Installing opentelemetry-operator
 INFO  Required prerequisites met!
 INFO  Proceeding with Upbound Spaces installation...
  ✓   [1/3]: Creating pull secret upbound-pull-secret
  ✓   [2/3]: Initializing Space components
  ✓   [3/3]: Starting Space Components
  🙌  Your Upbound Space is Ready!

  👀  Next Steps 👇

👉 Check out Upbound Spaces docs @ https://docs.upbound.io/concepts/upbound-spaces
```

### CODE REVIEW

File: cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go [hunk 1]
```diff
@@ -117,7 +119,33 @@ func (o *OpenTelemetryCollectorOperator) Install() error {
...
+
+	// wait until the operator pod is ready because Spaces
+	// OpenTelemetryCollector needs the mutating webhook to be ready
+	// to not fail the installation.
+	return o.waitUntilReady()
+}
+
+// waitUntilReady waits until the opentelemetry-operator pod is ready, or
+// until the timeout.
+func (o *OpenTelemetryCollectorOperator) waitUntilReady() error {
```
Comment (turkenh) [inline cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go:134]: nit: This looks like a very generic function, did you check if there are already existing methods you can leverage here?

**Review by turkenh — APPROVED** [review]

File: cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go [hunk 2]
```diff
@@ -117,7 +119,33 @@ func (o *OpenTelemetryCollectorOperator) Install() error {
...
+	return errors.Wrap(wait.PollUntilContextTimeout(context.Background(), 2*time.Second, 30*time.Second, true, func(ctx context.Context) (bool, error) {
```
Comment (sttts) [inline cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go:135]: Would output make sense? 30s is a long time. Would rather prefer waiting infinitely, but output something.

File: cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go (hunk 1 above)
Comment (lsviben) [reply cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go:136]: Didnt find a replacement for the whole thing, but found an existing way to check if the pod is ready. `podutils.IsPodReady(pod)`

File: cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go (hunk 2 above)
Comment (lsviben) [reply cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go:137]: On my machine its usually around 14s for the whole installation and check to finish, but of course that can vary. 
There is already a spinner and a timer with seconds to see what is going on. Added an output, LMK if it looks good:
```bash
 _output/bin/darwin_arm64/up space init --token-file="../key.json" "v1.4.0-rc.0.331.g417a41db" \
  --set "account=bob" \
  --set "features.alpha.observability.enabled=true"
 INFO  Setting defaults for vanilla Kubernetes (type kind)
 WARNING  One or more required prerequisites are not installed:

❌ cert-manager
❌ universal-crossplane
❌ ingress-nginx
❌ provider-kubernetes
❌ provider-helm
❌ opentelemetry-operator

Would you like to install them now? [y/N]: Yes

  ✓   [1/6]: Installing cert-manager
  ✓   [2/6]: Installing universal-crossplane
  ✓   [3/6]: Installing ingress-nginx
  ✓   [4/6]: Installing provider-kubernetes
  ✓   [5/6]: Installing provider-helm
 INFO  Waiting for opentelemetry-operator pod to get ready...
 INFO  Waiting for opentelemetry-operator pod to get ready...
 INFO  Waiting for opentelemetry-operator pod to get ready...
 INFO  Waiting for opentelemetry-operator pod to get ready...
 INFO  Waiting for opentelemetry-operator pod to get ready...
  ✓   [6/6]: Installing opentelemetry-operator
 INFO  Required prerequisites met!
 INFO  Proceeding with Upbound Spaces installation...
  ✓   [1/3]: Creating pull secret upbound-pull-secret
  ✓   [2/3]: Initializing Space components
  ✓   [3/3]: Starting Space Components
  🙌  Your Upbound Space is Ready!

  👀  Next Steps 👇

👉 Check out Upbound Spaces docs @ https://docs.upbound.io/concepts/upbound-spaces
```

Comment (sttts) [reply cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go:137]: If this is a 14s operation, waiting only 30s seems wrong. Under load this can take longer, leading to a bad experience, especially when part of an automation.

I still think we should wait infinitely.

Comment (lsviben) [reply cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go:137]: Ok I can change it to infinity 👍

File: cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go [hunk 3]
```diff
@@ -117,7 +121,33 @@ func (o *OpenTelemetryCollectorOperator) Install() error {
...
+		pods, err := o.kclient.CoreV1().Pods(chartName).List(ctx, metav1.ListOptions{
+			LabelSelector: "app.kubernetes.io/name=opentelemetry-operator",
+		})
+		if err != nil || pods == nil || len(pods.Items) != 1 {
+			pterm.Info.Println("Cant find opentelemetry-operator pod...")
```
Comment (turkenh) [inline cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go:142]: `can't` or `cannot` ? 

Would it make sense to print `err` if there is an error?

Comment (lsviben) [reply cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go]: makes sense, added a separate error check and print

File: cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go (hunk 2 above)
Comment (turkenh) [reply cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go]: Bumped to 10 mins.
