### PR TITLE
Move control plane commands to only support previously experimental API

### LINKED ISSUE #262: [main] Error on controlplane (ctp) commands
### What happened?
The `up controlplane` commands are erroring out with the latest builds from main.

After a quick triage it appears the "experimental" parameters weren't removed from some of the hooks, e.g. https://github.com/upbound/up/blob/fde467c4405d13781b7ab00ab2f9be8411eb0d05/cmd/up/controlplane/list.go#L34

### How can we reproduce it?
Example:
```
➜  ./up ctp list
up: error: couldn't find binding of type bool for parameter 0 of controlplane.listCmd.AfterApply(), use kong.Bind(bool)
```

Example (with alpha variant):
```
➜ ./up alpha ctp kubeconfig get luop-test --token=`cat ~/Desktop/luop`

up: error: couldn't find binding of type bool for parameter 0 of kubeconfig.getCmd.AfterApply(), use kong.Bind(bool)
```

### What environment did it happen in?
up version: `v0.14.0-rc.0.21.gfde467c`

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Updates all the control plane commands to use what previously was
enabled with UP_MCP_EXPERIMENTAL, but is not the only supported control
plane API.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Fixes #262 #263

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

Verified that the following commands now function properly without `UP_MCP_EXPERIMENTAL`:
- `up ctp list`
- `up ctp delete`
- `up ctp kubeconfig get`

### CODE REVIEW

File: internal/upbound/context.go [hunk 1]
```diff
@@ -41,6 +41,10 @@ const (
 	apiSubdomain = "api."
 	// Default proxy subdomain.
 	proxySubdomain = "proxy."
+
+	// Base path for proxy.
+	proxyPath = "/v1/controlPlanes"
```
Comment (jastang) [inline internal/upbound/context.go:46]: ah nice refactor here 👍🏼

**Review by jastang — APPROVED** [review]
LGTM!

**Review by tnthornton — APPROVED** [review]
